#!/usr/bin/env bash
set -o errexit

ROOT=$(git rev-parse --show-toplevel)

while IFS= read -r mock; do
    rm -f "$ROOT/$mock"
done < <(
    git -C "$ROOT" grep -l -F "Code generated by mockery" -- go-controller/pkg || true
)

make -C "$ROOT/go-controller" mocksgen
git -C "$ROOT" diff --exit-code -- go-controller/pkg
